### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [snyk/snyk-sbt-plugin#40]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/snyk/snyk-sbt-plugin/blob/master/package.json#L39-L41

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

Same for `child_process` and `path`.

**Comment by lili2311** [comment]
Fixed!
