### ISSUE TITLE
Update travis tests to use stages + add support for java 8, 9, 10 & 11

### ISSUE THREAD

**Issue by lili2311** [snyk/snyk-sbt-plugin#60]
### Expected behaviour
The code is tested on various java & sbt versions

### Actual behaviour
Only default java version is tested with various sbt versions

### Example
Here is an example travis config that would be ideal: https://github.com/snyk/snyk-gradle-plugin/pull/84/files

**Comment by sfat** [comment]
@lili2311,
I can take this, if that's okay.

**Comment by lili2311** [comment]
Please do :)

**Comment by sfat** [comment]
Just let me know what sbt versions are supported so I can have a baseline to start with?
Maybe we can decide in this ticket what matrix travis should have before I jump into it?

**Comment by lili2311** [comment]
Yep of course forgot to add this in: `0.13` `1.2.8`

**Comment by sfat** [comment]
Following with a similar pattern as to the mvn-plugin, does this look okay?

### stage 1 (current sbt version - 1.2.8):
node 6 => java 9
node 8 => java 10
node 10 => java 11
### stage 2 (0.13 + 1.2.8)
node 8 => java 8 (0.13)
node 8 => java 10 (0.13)
node 8 => java 11 (0.13)
node 8 => java 12 (0.13)
node 8 => java 13 (0.13)
node 8 => java 8 (1.2.8)
node 8 => java 12 (1.2.8)

**Comment by lili2311** [comment]
Not sure it is worth testing 0.13 + java 13 / java 12 maybe 1.2.8 instead? otherwise 👍

**Comment by sfat** [comment]
Yeah, makes sense :) I’ve updated the list

**Comment by sfat** [comment]
Should I use sdkman for this?
I see that sdkman only know from 0.13.9, while one of the test projects is set to sbt.version=0.13.7 (looking at `snyk-sbt-plugin/test/fixtures/testproj-0.13/project/build.properties`)
```
sdk list sbt
================================================================================
Available Sbt Versions
================================================================================
     1.3.0-RC1           1.1.0
     1.2.8               1.0.4
     1.2.7               1.0.3
     1.2.6               1.0.2
     1.2.5               1.0.1
     1.2.4               1.0.0
     1.2.3               0.13.18
     1.2.1               0.13.15
     1.2.0               0.13.13
     1.1.6               0.13.12
     1.1.5               0.13.11
     1.1.4               0.13.9
     1.1.3
     1.1.2
     1.1.1
```
Is that okay or look at https://github.com/paulp/sbt-extras ? I see that is being used in the current travis setup.

**Comment by lili2311** [comment]
So the test fixtures already pin the `sbt` e.g. https://github.com/snyk/snyk-sbt-plugin/blob/master/test/fixtures/testproj-noplugin-0.13/project/build.properties 
so the travis setup can just be about java versions. Unless we completely restructure the tests to use system sbt version which can be another time!
