### ISSUE TITLE
The problem with passing --configuration runtimeClasspath

### ISSUE THREAD

**Issue by meldmy** [snyk/snyk-sbt-plugin#71]
- `sbt -v`:  1.3.3

- What command was run(including all the options):
`snyk monitor --org=49dab540-aead-4062-ba80-349514981aaf --project-name=pricing_service -- --configuration runtimeClasspath`

### Expected behaviour
snyk should scan only runtimeClasspath dependencies in sbt.

### Actual behaviour
I have the following output: 

> [info] Loading settings for project promotions-root from build.sbt ...
> [info] Set current project to service (in build file:/path/myProject/)
> [error] Expected ';'
> [error] --configuration
> [error]                ^
>  null
> 
> Please make sure that the `sbt-dependency-graph` plugin (https://github.com/jrudolph/sbt-dependency-graph) is installed globally or on the current project, and that `sbt "-Dsbt.log.noformat=true" --configuration runtimeClasspath dependencyTree` executes successfully on this project.
> 
> Alternatively you can use `sbt-coursier` for dependency resolution (https://get-coursier.io/docs/sbt-coursier), in which case ensure that the plugin is installed on the current project and that `sbt "-Dsbt.log.noformat=true" --configuration runtimeClasspath coursierDependencyTree` executes successfully on this project.
> 
> For this project we guessed that you are using sbt-dependency-graph.
> 
> If the problem persists, collect the output of `sbt "-Dsbt.log.noformat=true" --configuration runtimeClasspath dependencyTree` or `sbt "-Dsbt.log.noformat=true" --configuration runtimeClasspath coursierDependencyTree` and contact support@snyk.io

### Steps to reproduce
I've added the required plugin to SBT build file:
`addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")`

run the following command:
`snyk monitor --org=49dab540-aead-4062-ba80-349514981aaf --project-name=pricing_service -- --configuration runtimeClasspath`

---

If applicable, please append the `-d` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by lili2311** [comment]
👋 is this still an issue for you with latest CLI version?

**Comment by ProntoHiran** [comment]
I am having the same issue, were you able to solve this?

**Comment by lili2311** [comment]
@ProntoHiran is the latest CLI version still a problem for you? Please can you try it?

**Comment by lili2311** [comment]
@ProntoHiran closing this, please re-open if this is still an issue
